# 프론트엔드/백엔드 애플리케이션을 어떻게 실행할지 정의

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-app
spec:
  replicas: 2 # 안정성을 위해 2개를 실행
  selector:
    matchLabels:
      app: tetris-app
  template:
    metadata:
      labels:
        app: tetris-app
    spec:
      containers:
      - name: tetris-container
        # CI 파이프라인이 ACR에 올린 통합(프론트/백) 이미지를 사용
        image: tetrisgameacr.azurecr.io/tetris-app:1.0.0
        ports:
        # server.js가 사용하는 3000번 포트 하나만 열면 됨
        - containerPort: 3000