apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-tetris-secrets
  namespace: tetris-app
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "3b0188f3-3986-4e7a-9460-071c9db29815"
    keyvaultName: "tetris-camp-kv-amx6"
    tenantId: "08e11a23-5080-466e-91db-8b235f6a26d7"
    objects: |
      array:
        - |
          objectName: postgresql-url
          objectType: secret
          objectAlias: postgresql-url
        - |
          objectName: db-database
          objectType: secret
          objectAlias: db-database
        - |
          objectName: db-host
          objectType: secret
          objectAlias: db-host
        - |
          objectName: db-password
          objectType: secret
          objectAlias: db-password
        - |
          objectName: db-port
          objectType: secret
          objectAlias: db-port
        - |
          objectName: db-user
          objectType: secret
          objectAlias: db-user
        - |
          objectName: redis-host
          objectType: secret
          objectAlias: redis-host
        - |
          objectName: redis-pass
          objectType: secret
          objectAlias: redis-pass
        - |
          objectName: jwt-secret
          objectType: secret
          objectAlias: jwt-secret
        - |
          objectName: refresh-token-secret
          objectType: secret
          objectAlias: refresh-token-secret
  secretObjects:
  - secretName: app-secrets
    type: Opaque
    data:
    - objectName: postgresql-url
      key: postgresql-url
    - objectName: redis-host
      key: redis-host
    - objectName: redis-pass
      key: redis-pass
    - objectName: jwt-secret
      key: jwt-secret
    - objectName: refresh-token-secret
      key: refresh-token-secret