apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-tetris-secrets
spec:
  provider: azure
  parameters:
    keyvaultName: "tetrisgame-kv"
    tenantId: "..."
    objects: |
      array:
        - |
          objectName: postgresql-url
          objectType: secret
        - |
          objectName: redis-host
          objectType: secret
        # ... (가져올 모든 비밀 목록)