apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-tetris-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "" # AKS Key Vault Secrets Provider의 Identity ID가 자동으로 설정됨
    keyvaultName: "tetrisgame-kv-xxxx" # Terraform에서 생성된 Key Vault 이름으로 교체 필요
    tenantId: "your-tenant-id-here"     # Azure 테넌트 ID로 교체 필요
    objects: |
      array:
        - |
          objectName: postgresql-url
          objectType: secret
          objectAlias: postgresql-url
        - |
          objectName: redis-host
          objectType: secret
          objectAlias: redis-host
        - |
          objectName: redis-pass
          objectType: secret
          objectAlias: redis-pass
        - |
          objectName: jwt-secret
          objectType: secret
          objectAlias: jwt-secret
        - |
          objectName: refresh-token-secret
          objectType: secret
          objectAlias: refresh-token-secret
  secretObjects:
  - secretName: app-secrets
    type: Opaque
    data:
    - objectName: postgresql-url
      key: postgresql-url
    - objectName: redis-host
      key: redis-host
    - objectName: redis-pass
      key: redis-pass
    - objectName: jwt-secret
      key: jwt-secret
    - objectName: refresh-token-secret
      key: refresh-token-secret