# 공인 IP 주소를 할당

apiVersion: v1
kind: Service
metadata:
  name: tetris-service
spec:
  # LoadBalancer 타입으로 설정해야 외부 IP가 할당됨
  type: LoadBalancer
  selector:
    # 'app: tetris-app' 라벨이 붙은 Pod(Deployment가 만든)을 찾아 연결함
    app: tetris-app
  ports:
    - name: http
      protocol: TCP
      # 외부에서 80번 포트로 들어오는 요청을
      port: 80
      # 컨테이너의 3000번 포트로 전달
      targetPort: 3000
